delete from servico;

ALTER TABLE servico ALTER COLUMN codigoservico RESTART WITH 1;

INSERT INTO SERVICO (VALORSERVICO, NOMESERVICO, TIPOSERVICO) VALUES (312, 'Acordo', 'esporadico');
INSERT INTO SERVICO (VALORSERVICO, NOMESERVICO, TIPOSERVICO) VALUES (283, 'Conservação do salão', 'esporadico');
INSERT INTO SERVICO (VALORSERVICO, NOMESERVICO, TIPOSERVICO) VALUES (84.60, 'Vaga Carro / Moto', 'frequente');
INSERT INTO SERVICO (VALORSERVICO, NOMESERVICO, TIPOSERVICO) VALUES (169.60, '2x Vaga Carro / Moto', 'frequente');


select * from servico;
